# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x04\x62ook\"\x1b\n\rBookIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty\"F\n\x0c\x42ookResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x18\n\x10publication_date\x18\x03 \x01(\t\"T\n\x0e\x42ookResponseID\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x18\n\x10publication_date\x18\x04 \x01(\t\"6\n\x10ListBookResponse\x12\"\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x14.book.BookResponseID2\x99\x02\n\x04\x42ook\x12\x36\n\x07GetBook\x12\x13.book.BookIdRequest\x1a\x14.book.BookResponseID\"\x00\x12\x31\n\x08ListBook\x12\x0b.book.Empty\x1a\x16.book.ListBookResponse\"\x00\x12\x38\n\nCreateBook\x12\x12.book.BookResponse\x1a\x14.book.BookResponseID\"\x00\x12:\n\nUpdateBook\x12\x14.book.BookResponseID\x1a\x14.book.BookResponseID\"\x00\x12\x30\n\nDeleteBook\x12\x13.book.BookIdRequest\x1a\x0b.book.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKIDREQUEST']._serialized_start=20
  _globals['_BOOKIDREQUEST']._serialized_end=47
  _globals['_EMPTY']._serialized_start=49
  _globals['_EMPTY']._serialized_end=56
  _globals['_BOOKRESPONSE']._serialized_start=58
  _globals['_BOOKRESPONSE']._serialized_end=128
  _globals['_BOOKRESPONSEID']._serialized_start=130
  _globals['_BOOKRESPONSEID']._serialized_end=214
  _globals['_LISTBOOKRESPONSE']._serialized_start=216
  _globals['_LISTBOOKRESPONSE']._serialized_end=270
  _globals['_BOOK']._serialized_start=273
  _globals['_BOOK']._serialized_end=554
# @@protoc_insertion_point(module_scope)
